# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Moleculer.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: rm -rf .env
    - name: Make envfile
      run: npx create-env --env-file .env --env-prefix PROD_
      env: 
        PROD_SENDGRID_API_KEY: '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'
        PROD_SENDER_EMAIL_ADDRESS: 'info@catfriendlysofa.com'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: pm2 restart CATAPI
